language: node_js
node_js:
- lts/*
install: |-
  npm ci
  npm install -g codecov
script: |-
  npm run build-prod || travis_terminate 1
  ./node_modules/.bin/nyc report --reporter lcovonly -- -R spec
  codecov
  log=$(git log $TRAVIS_COMMIT_RANGE --oneline)
  echo $'Commit message: '$TRAVIS_COMMIT_MESSAGE
  echo $'**Change log:**<br/>'${log//$'\n'/<br/>}
branches:
  only:
  - master
before_deploy: |-
  log=$(git log $TRAVIS_COMMIT_RANGE --oneline)
  export TAG=$'v'$TRAVIS_COMMIT_MESSAGE
  export BODY=$'**Change log:**<br/>'${log//$'\n'/<br/>}
  openssl aes-256-cbc -K $encrypted_187c157010cd_key -iv $encrypted_187c157010cd_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  eval "$(ssh-agent -s)"
  chmod 600 /tmp/deploy_rsa
  ssh-add /tmp/deploy_rsa
deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: x5JoKd+SCOSyZ36jY/iUSpbia6K4d2EbQUoWjq4m0sQkPnFXCl9QnDwP9vynMD3Yav+5kGxyan+4Pe3b6AZG/dzkHfmI8s+w7a/E6+Moc67Hz0uYnlT/7Z8zLTv4Nji/UhPR8LF3YYSYFo9F+GNAWNC6oQPJKRpLzxsUPfTo77tG8vdnFPByB/9fbLcv8cn8FfP6j4x+Z1slCwI3zEg9iyKqh57q911wYjPy6Vl8Il1RyL6nC1EJkoPfOixepUTqRW7lnhaT+3b6W/Xp4/WUvgmXhkTPiSb6I063hZcJohN1Q+FmKU3rd5lG+gmSK9hGvojluBi6yD0t7lnn4J09UpgWc7A6POJ3qaopAeMiqlN1/L4kJjRJI8A2VS+b2YjpZldcl5bLMEiagopBOctd6pHp2yOFbx4aWz0ObnVvUWlJs8yLaTW0aMsdKZIohv2cuw4bDfkn5SHfBvg2lZRwRdGzzCUZB2FFZUGjsTjlkM6HMtMQ5HOXXJ67RPA7i5KA4is8B4s9BcE/bmGi5+KDPiAOKl45eEVR/XJgViXDL0YnqnFSJWp5LbfizTzhy2Tyblij6bnyypLWKSNImJOAKAc3+WEHbLFE0EEvlYPOxIngyTIsW55Yomlgg/fPPF5BHRM/TugBCcEACcWNiqCGdlgwCgc4XFv+X4NT9mCMvc4=
    file: README.md
    name: Release $TRAVIS_COMMIT_MESSAGE
    tag_name: "$TAG"
    body: "$BODY"
    on:
      repo: Guseyn/guseyn.com
      branch:
        - master
      condition: "$TRAVIS_COMMIT_MESSAGE =~ ^([0-9]{1,3}).([0-9]{1,3}).([0-9]{1,3})$"
  - provider: script
    skip_cleanup: true
    script: bash deploy.sh
    on:
      repo: Guseyn/guseyn.com
      branch:
        - master
      condition: "$TRAVIS_COMMIT_MESSAGE =~ ^([0-9]{1,3}).([0-9]{1,3}).([0-9]{1,3})$"
after_deploy: |-
  bash run.sh
