version: '3.8'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: guseyn.com
    volumes:
      - ./output.log:/app/output.log
      - ./nodes:/app/nodes
      - ./guseyn.com:/app/guseyn.com
      - ./guseyn.com/.well-known/acme-challenge:/app/.well-known/acme-challenge  # Mount ACME challenge folder
      - ./guseyn.com/ssl:/app/guseyn.com/ssl  # Mount folder for SSL certs inside app/guseyn.com/ssl
    ports:
      - "8001:8001"
    networks:
      - app-network
    # Override CMD in Dockerfile with my ENV variable
    command: sh -c "npm run guseyn:local:start"

networks:
  app-network:
    driver: bridge
