version: '3.8'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: guseyn.com
    volumes:
      - ./output.log:/app/output.log
      - ./nodes:/app/nodes
      - ./web-app:/app/web-app
      - ./web-app/.well-known/acme-challenge:/app/web-app/.well-known/acme-challenge  # Mount ACME challenge folder
      - ./web-app/ssl:/app/web-app/ssl  # Mount folder for SSL certs inside app/guseyn.com/ssl
    ports:
      - "443:443"  # Prime HTTP(S)/2 
      - "80:80"   # Proxy
    networks:
      - app-network
    # Override CMD in Dockerfile with my ENV variable
    command: sh -c "npm run guseyn:prod:start"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://174.138.15.193:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  certbot:
    image: certbot/certbot
    container_name: certbot
    depends_on:
      - app
    volumes:
      - ./web-app/.well-known/acme-challenge:/.well-known/acme-challenge  # ACME challenge folder
      - ./web-app/ssl:/etc/letsencrypt  # Mount SSL cert folder
    command: >
      certonly
      --non-interactive
      --webroot
      --webroot-path=/.well-known/acme-challenge
      --email ${DOMAIN_EMAIL}
      --agree-tos
      -d ${DOMAIN},www.${DOMAIN}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
